### ISSUE TITLE
Support additional Dynatrace Event Types

### ISSUE THREAD

**Issue by robertjahn** [dynatrace-oss/dynatrace-github-action#107]
Currently only CUSTOM_INFO is supported.  Please support all 5 available types in the API, but the higher priority is to support the `CUSTOM_DEPLOYMENT` type

https://www.dynatrace.com/support/help/dynatrace-api/environment-api/events/post-event/

**Comment by robertjahn** [comment]
I think all that is needed for this is the following to the `dynatrace.ts` script

```

export interface Event {
  type: string;
  title: string;
  description: string;
  source: string;
  entities?: string[];
  tags?: string[];
  dimensions?: Map<string, string>;
  deploymentName: string;
  deploymentVersion: string;
  annotationType: string;
  annotationDescription: string;
  configuration: string;
  original: string;
  ciBackLink: string;
}

 // create Dynatrace event structure
    var event = {};

    switch (e.type) {
      case 'CUSTOM_INFO':
        event = {
          eventType: e.type,
          attachRules: {
            entityIds: e.entities,
            tagRule: tagAttachRules
          },
          source: e.source,
          description: e.description,
          title: e.title,
          customProperties: e.dimensions
        }
        break;
      case 'CUSTOM_DEPLOYMENT':
        event = {
          eventType: e.type,
          attachRules: {
            entityIds: e.entities,
            tagRule: tagAttachRules
          },
          source: e.source,
          customProperties: e.dimensions,
          deploymentName: e.deploymentName,
          deploymentVersion: e.deploymentVersion,
          ciBackLink: e.ciBackLink
        }
        break;
      case 'CUSTOM_ANNOTATION':
        event = {
          eventType: e.type,
          attachRules: {
            entityIds: e.entities,
            tagRule: tagAttachRules
          },
          source: e.source,
          customProperties: e.dimensions,
          description: e.description,
          annotationType: e.annotationType,
          annotationDescription: e.annotationDescription
        }
        break;
      case 'CUSTOM_CONFIGURATION':
        event = {
          eventType: e.type,
          attachRules: {
            entityIds: e.entities,
            tagRule: tagAttachRules
          },
          source: e.source,
          customProperties: e.dimensions,
          original: e.original,
          configuration: e.configuration
        }
        break;
      case 'MARKED_FOR_TERMINATION':
        event = {
          eventType: e.type,
          attachRules: {
            entityIds: e.entities,
            tagRule: tagAttachRules
          },
          source: e.source,
          customProperties: e.dimensions,
          ciBackLink: e.ciBackLink,
          description: e.description,
          title: e.title,
        }
        break;
      default:
        throw new Error(`Invalid event type`);
    }
```

**Comment by robertjahn** [comment]
Here is what I think would work for an additional test in `test.yml`

```
  test: # test each event type
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test CUSTOM_INFO
        uses: ./
        with:
          url: '${{ secrets.DT_URL }}'
          token: '${{ secrets.DT_TOKEN }}'
          events: |
            - title: "Test CUSTOM_INFO"
              type: CUSTOM_INFO    
              description: "Test CUSTOM_INFO"
              source: GitHub
              entities:
                - MOBILE_APPLICATION-C061BED4799B41C5
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: wolfgang
      - name: Test CUSTOM_DEPLOYMENT
        uses: ./
        with:
          url: '${{ secrets.DT_URL }}'
          token: '${{ secrets.DT_TOKEN }}'
          events: |
            - title: "Test CUSTOM_DEPLOYMENT"
              type: CUSTOM_DEPLOYMENT    
              deploymentName: "Test CUSTOM_DEPLOYMENT version 1"
              deploymentVersion: 1
              ciBackLink: "http://www.dynatrace.com"
              source: GitHub
              entities:
                - MOBILE_APPLICATION-C061BED4799B41C5
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: wolfgang
      - name: Test CUSTOM_ANNOTATION
        uses: ./
        with:
          url: '${{ secrets.DT_URL }}'
          token: '${{ secrets.DT_TOKEN }}'
          events: |
            - title: "Test CUSTOM_ANNOTATION"
              type: CUSTOM_ANNOTATION    
              description: "Test CUSTOM_ANNOTATION"
              annotationType: "Test CUSTOM_ANNOTATION annotationType"
              annotationDescription: "Test CUSTOM_ANNOTATION annotationDescription"
              source: GitHub
              entities:
                - MOBILE_APPLICATION-C061BED4799B41C5
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: wolfgang
      - name: Test CUSTOM_CONFIGURATION
        uses: ./
        with:
          url: '${{ secrets.DT_URL }}'
          token: '${{ secrets.DT_TOKEN }}'
          events: |
            - title: "Test CUSTOM_CONFIGURATION"
              type: CUSTOM_CONFIGURATION    
              original: "Test CUSTOM_CONFIGURATION original"
              configuration: "Test CUSTOM_CONFIGURATION configuration"
              source: GitHub
              entities:
                - MOBILE_APPLICATION-C061BED4799B41C5
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: wolfgang
      - name: Test MARKED_FOR_TERMINATION
        uses: ./
        with:
          url: '${{ secrets.DT_URL }}'
          token: '${{ secrets.DT_TOKEN }}'
          events: |
            - title: "Test MARKED_FOR_TERMINATION"
              type: MARKED_FOR_TERMINATION    
              description: "Test MARKED_FOR_TERMINATION"
              ciBackLink: "http://www.dynatrace.com"
              source: GitHub
              entities:
                - MOBILE_APPLICATION-C061BED4799B41C5
              dimensions:
                project: "${{ github.repository }}"
                branch: "${{ github.ref }}"
                event: "${{ github.event_name }}"
                owner: wolfgang
```
