### ISSUE TITLE
Add option to fail for tags that do not match

### ISSUE THREAD

**Issue by robertjahn** [dynatrace-oss/dynatrace-github-action#108]
Currently if you pass in a tag rule that does not match an entity, you get an error message in the github action log that is not obvious that this was the problem.   I would like to see the message returned from the API or message like `no entities matched`.  And since, I may or may not want to stop the pipeline on a non-matching request I would like to see an option like `nomatch: fail` and `nomatch:ignore` as part of the action definition.

Here is an example log when the tag did not match:

```
Run dynatrace-oss/dynatrace-github-action@v5
  with:
    url: ***
    token: ***
    events: - title: "dt-orders frontend deployment"
    type: CUSTOM_INFO
    description: "dt-orders frontend deployment"
    source: GitHub
    tags:
      - SERVICE:service:frontendBAD
    dimensions:
      project: "dt-demos/github-actions"
      branch: "refs/heads/main"
      event: "workflow_dispatch"
    owner: dt-demos
  
    metrics: []
  env:
    REGISTRY_NAME: dtdemos
    CLUSTER_NAME: jahn-aks-demo
    CLUSTER_RESOURCE_GROUP: jahn-aks-demo
    NAMESPACE: dt-orders
    KUBECONFIG: /home/runner/work/_temp/kubeconfig_1622574887606
[]
- title: "dt-orders frontend deployment"
  type: CUSTOM_INFO
  description: "dt-orders frontend deployment"
  source: GitHub
  tags:
    - SERVICE:service:frontendBAD
  dimensions:
    project: "dt-demos/github-actions"
    branch: "refs/heads/main"
    event: "workflow_dispatch"
  owner: dt-demos
Sending 1 events
***"eventType":"CUSTOM_INFO","attachRules":***"tagRule":[***"meTypes":["SERVICE"],"tags":[***"context":"CONTEXTLESS","key":"service","value":"frontendBAD"***]***]***,"source":"GitHub","description":"dt-orders frontend deployment","title":"dt-orders frontend deployment","customProperties":***"project":"dt-demos/github-actions","branch":"refs/heads/main","event":"workflow_dispatch"***
(node:2008) UnhandledPromiseRejectionWarning: Error: HTTP request failed: Bad Request
    at Object.<anonymous> (/home/runner/work/_actions/dynatrace-oss/dynatrace-github-action/v5/webpack:/typescript-action/lib/dynatrace.js:134:1)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/dynatrace-oss/dynatrace-github-action/v5/webpack:/typescript-action/lib/dynatrace.js:24:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
